feat: event details page
Foodrive/foodspot-mobile-client pull request #23
Opened 2021-08-09 14:49 UTC by GitAndrew

2021-08-13 12:25 UTC, winniezheng approved these changes

2021-08-14 23:05 UTC, chrisrabe requested changes
reverse parameter has an incorrect default value type

2021-08-14 23:05 UTC, chrisrabe commented on src/components/ui/IconButton/index.tsx
> +  reverse = "true",
isn't reverse a boolean? How come it's being assigned a string as its default

2021-08-14 23:20 UTC, chrisrabe approved these changes
Nice

2021-08-14 23:20 UTC, merged