feat: homescreen search by name
Foodrive/foodspot-mobile-client pull request #33
Opened 2021-08-30 11:33 UTC by winniezheng

2021-08-31 07:07 UTC, GitAndrew approved these changes

2021-08-31 07:24 UTC, chrisrabe requested changes
Can we update the placeholder text of the search input to be "Search by name" instead of "Search by location"?

2021-09-02 03:41 UTC, winniezheng commented
> Can we update the placeholder text of the search input to be "Search by name" instead of "Search by location"?

done

2021-09-04 06:09 UTC, chrisrabe approved these changes
Nice

2021-09-04 06:09 UTC, merged