feat: reusable list item
Foodrive/foodspot-mobile-client pull request #4
Opened 2021-07-19 04:02 UTC by winniezheng

2021-07-19 10:53 UTC, winniezheng commented
Example use:
const list = [
  {
    name: "Amy Farha",
    avatar_url:
      "https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg",
    subtitle: "Vice President",
  },
  {
    name: "Chris Jackson",
    avatar_url:
      "https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg",
    subtitle: "Vice Chairman",
  },
];

  <View>
    {list.map((l, i) => (
      <ListItem
        id={`${l.name}-${i}`}
        key={`${l.name}-${i}`}
        title={l.name}
        otherInformation={l.subtitle}
        showNav={true}
        iconName="md-basket"
      ></ListItem>
    ))}
  </View>

2021-07-19 12:25 UTC, chrisrabe requested changes
Just need default value for nav since most list item has that right chevron

2021-07-19 12:25 UTC, chrisrabe commented on src/components/ui/ListItem/index.tsx
> +  showNav: boolean; //show chevron right navigation icon
maybe we could add a default value to have this as true by default since most list item has it

2021-07-20 10:12 UTC, chrisrabe requested changes
use defaultProps property instead

https://blog.bitsrc.io/understanding-react-default-props-5c50401ed37d

2021-07-20 10:12 UTC, chrisrabe commented on src/components/ui/ListItem/index.tsx
> +const ListItem: React.FC<ListItemProps> = (props) => {
It's better to do it like this for default values. Also, make the ones with default values as optional props

```
ListItem.defaultProps = {
  iconName: "md-basket",
  showNav: true,
  iconColor: "grey",
  iconFamily: "ionicon"
}
```

2021-07-20 12:46 UTC, chrisrabe approved these changes
looks good

2021-07-20 12:46 UTC, merged